apiVersion: v1
kind: Service
metadata:
  name: video-detection-backend
  annotations:
    networking.gke.io/load-balancer-ip: "35.226.34.108"
spec:
  selector:
    app: video-detection-backend
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer