apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-detection-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: video-detection-frontend
  template:
    metadata:
      labels:
        app: video-detection-frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/video-detection-2024/video-detection-frontend:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
        - containerPort: 80